CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "students" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "number" varchar NOT NULL,
  "class_id" bigint 
);

CREATE TABLE "schools" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "name" varchar UNIQUE NOT NULL,
  "address" varchar NOT NULL
);

CREATE TABLE "classes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "name" varchar NOT NULL,
  "start_year" integer NOT NULL,
  "description" varchar,
  "school_id" bigint NOT NULL
);

CREATE TABLE "comments_associations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "entity_id" bigint NOT NULL,
  "comment_id" bigint NOT NULL,
  "comment_associate" varchar NOT NULL
);

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT 'now()',
  "user_id" bigint NOT NULL,
  "content" varchar,
  "visible" bool NOT NULL DEFAULT true
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "student_id" bigint NOT NULL,
  "name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "enabled" bool NOT NULL DEFAULT true,
  "expired" bool NOT NULL DEFAULT false,
  "deleted" bool NOT NULL DEFAULT false,
  "dek" bytea
);

CREATE TABLE "contributions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "value" numeric NOT NULL,
  "student_id" bigint NOT NULL,
  "target_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()'
);

CREATE TABLE "targets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "description" varchar,
  "summary" varchar,
  "due_to" date NOT NULL,
  "estimated_value" numeric NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()'
);

CREATE TABLE "polls_questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "question" varchar NOT NULL,
  "poll_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()'
);

CREATE TABLE "polls_answers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "poll_question_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "student_id" bigint NOT NULL,
  "user_id" bigint NOT NULL
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public" uuid UNIQUE DEFAULT gen_random_uuid(),
  "summary" varchar,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "user_id" bigint NOT NULL,
  "is_read" bool NOT NULL DEFAULT false
);

CREATE TABLE "announcements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "user_id" bigint NOT NULL,
  "is_read" bool NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "description" varchar,
  "summary" varchar,
  "published_at" timestamp NOT NULL DEFAULT 'now()'
);

CREATE TABLE "roles" (
  "role" varchar PRIMARY KEY
);

CREATE TABLE "user_roles" (
  "role" varchar NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("role", "user_id")
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT gen_random_uuid(),
  "date" timestamp NOT NULL DEFAULT 'now()',
  "user_id" bigint NOT NULL,
  "contribution_id" bigint NOT NULL,
  "value" numeric NOT NULL,
  "is_success" bool NOT NULL,
  "rejected" bool NOT NULL,
  "returned" bool NOT NULL,
  "vendor_id" varchar NOT NULL,
  "payment_type" varchar NOT NULL
);

COMMENT ON COLUMN "comments_associations"."comment_associate" IS 'enum type';

COMMENT ON COLUMN "payments"."payment_type" IS 'blik or sth else';

ALTER TABLE "students" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "classes" ADD FOREIGN KEY ("school_id") REFERENCES "schools" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("contribution_id") REFERENCES "contributions" ("id");

ALTER TABLE "contributions" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "announcements" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "polls_answers" ADD FOREIGN KEY ("poll_question_id") REFERENCES "polls_questions" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role") REFERENCES "roles" ("role");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "polls_answers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "polls_answers" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "comments_associations" ADD FOREIGN KEY ("comment_id") REFERENCES "comments" ("id");

ALTER TABLE "contributions" ADD FOREIGN KEY ("target_id") REFERENCES "targets" ("id");
