CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE "students" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "number" string NOT NULL,
  "class_id" bigint
);

CREATE TABLE "schools" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "name" string UNIQUE NOT NULL,
  "address" string NOT NULL
);

CREATE TABLE "classes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "name" string NOT NULL,
  "start_year" integer NOT NULL,
  "description" string,
  "school_id" bigint NOT NULL
);

CREATE TABLE "comments_associations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "entity_id" bigint NOT NULL,
  "comment_id" bigint NOT NULL,
  "comment_associate" string NOT NULL
);

CREATE TABLE "comments" (
  "id" uuid PRIMARY KEY,
  "created_at" datetime DEFAULT 'now()',
  "user_id" bigint NOT NULL,
  "content" string,
  "visible" bool NOT NULL DEFAULT true
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "student_id" bigint NOT NULL,
  "name" string,
  "email" string UNIQUE NOT NULL,
  "phone" string UNIQUE NOT NULL,
  "password" string NOT NULL,
  "enabled" bool NOT NULL DEFAULT true,
  "expired" bool NOT NULL DEFAULT false,
  "deleted" bool NOT NULL DEFAULT false,
  "dek" bytea
);

CREATE TABLE "contributions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "value" numeric NOT NULL,
  "student_id" bigint NOT NULL,
  "target_id" bigint NOT NULL,
  "created_at" datetime NOT NULL DEFAULT 'now()'
);

CREATE TABLE "targets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "description" string,
  "summary" string,
  "due_to" date NOT NULL,
  "estimated_value" numeric NOT NULL,
  "created_at" datetime NOT NULL DEFAULT 'now()'
);

CREATE TABLE "polls_questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "question" string NOT NULL,
  "poll_id" bigint NOT NULL,
  "created_at" datetime NOT NULL DEFAULT 'now()'
);

CREATE TABLE "polls_answers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "poll_question_id" bigint NOT NULL,
  "created_at" datetime NOT NULL DEFAULT 'now()',
  "student_id" bigint NOT NULL,
  "user_id" bigint NOT NULL
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "summary" string,
  "created_at" datetime NOT NULL DEFAULT 'now()',
  "user_id" bigint NOT NULL,
  "is_read" bool NOT NULL DEFAULT false
);

CREATE TABLE "announcements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "user_id" bigint NOT NULL,
  "is_read" bool NOT NULL DEFAULT false,
  "created_at" datetime NOT NULL DEFAULT 'now()',
  "description" string,
  "summary" string,
  "published_at" datetime NOT NULL DEFAULT 'now()'
);

CREATE TABLE "roles" (
  "role" string PRIMARY KEY
);

CREATE TABLE "user_roles" (
  "role" string NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("role", "user_id")
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE DEFAULT 'gen_random_uuid()',
  "date" datetime NOT NULL DEFAULT 'now()',
  "user_id" bigint NOT NULL,
  "contribution_id" bigint NOT NULL,
  "value" numeric NOT NULL,
  "is_success" bool NOT NULL,
  "rejected" bool NOT NULL,
  "returned" bool NOT NULL,
  "vendor_id" string NOT NULL,
  "payment_type" string NOT NULL
);

COMMENT ON COLUMN "comments_associations"."comment_associate" IS 'enum type';

COMMENT ON COLUMN "payments"."payment_type" IS 'blik or sth else';

ALTER TABLE "classes" ADD FOREIGN KEY ("id") REFERENCES "students" ("class_id");

ALTER TABLE "users" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "classes" ADD FOREIGN KEY ("school_id") REFERENCES "schools" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("contribution_id") REFERENCES "contributions" ("id");

ALTER TABLE "contributions" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "announcements" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "polls_answers" ADD FOREIGN KEY ("poll_question_id") REFERENCES "polls_questions" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role") REFERENCES "roles" ("role");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "polls_answers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "polls_answers" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("id") REFERENCES "comments_associations" ("comment_id");

ALTER TABLE "contributions" ADD FOREIGN KEY ("target_id") REFERENCES "targets" ("id");
