CREATE TABLE IF NOT EXISTS public.outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type varchar(255) NOT NULL,
    payload text NOT NULL,
    status varchar(32) NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    processed_at timestamp
);

CREATE INDEX IF NOT EXISTS idx_outbox_status_created ON public.outbox_events(status, created_at);
