-- Remove join_code column from users table
ALTER TABLE "users" DROP COLUMN IF EXISTS "join_code";

-- Create new table for student join codes
CREATE TABLE IF NOT EXISTS public.student_join_codes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT                      NOT NULL,
    user_id    BIGINT                      NULL,
    join_code  VARCHAR(64)                 NOT NULL UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_student_join_codes_student
        FOREIGN KEY (student_id)
            REFERENCES public.students (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_student_join_codes_user
        FOREIGN KEY (user_id)
            REFERENCES public.users (id)
            ON DELETE CASCADE
);

ALTER TABLE public.student_join_codes
    OWNER TO rada_user;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_student_join_codes_student_id
    ON public.student_join_codes (student_id);

CREATE INDEX IF NOT EXISTS idx_student_join_codes_user_id
    ON public.student_join_codes (user_id);

CREATE INDEX IF NOT EXISTS idx_student_join_codes_join_code
    ON public.student_join_codes (join_code);

-- Create unique constraint to ensure one join code per student-user pair
CREATE UNIQUE INDEX IF NOT EXISTS idx_student_join_codes_student_user
    ON public.student_join_codes (student_id, user_id);
